i18n.registerContent('de', 'level2', [
    {
        title: "Modell-Quantisierung",
        content: `<h3>Lesson outline</h3><ul><li>What quantization is: mapping float32 values to integers (int8, int16, uint8) using a scale factor and zero-point</li><li>Linear (uniform) quantization formula: $q = \text{round}\!\left(\frac{r}{s}\right) + z$, where $r$ is the real value, $s$ is scale, $z$ is zero-point</li><li>Dequantization: $r = s \cdot (q - z)$</li><li>Per-tensor vs. per-channel quantization: per-channel has a separate scale per output channel; more accurate, slightly more complex</li><li>Post-training quantization (PTQ): applied after training using a calibration dataset; fast but may lose accuracy</li><li>Quantization-aware training (QAT): inserts fake-quantization nodes during training so gradients account for rounding; recovers 1–4% accuracy lost by PTQ</li><li>Mixed precision: quantize compute-intensive layers to int8, keep sensitive layers (first/last) in float16 or float32</li><li>Pitfall: calibrating PTQ with too few samples (&lt; 100 representative samples leads to poor scale estimation)</li></ul><h3>Key takeaways</h3><ul><li>8-bit quantization reduces model size by 4× and memory bandwidth by 4×; can also accelerate inference 2–4× on hardware with SIMD int8 support</li><li>Scale $s = (r_{max} - r_{min}) / (2^b - 1)$ where $b$ is bit-width; zero-point $z = -\text{round}(r_{min} / s)$</li><li>QAT almost always outperforms PTQ for the same target bit-width</li><li>The first and last layers of a network are most sensitive to quantization — keep them at higher precision when using mixed precision</li><li>Int8 inference on Cortex-M55 (Helium) can achieve 4–8× speedup over float32 due to vectorized SIMD operations</li></ul>`,
        keyPoints: ["8-bit quantization reduces model size by 4\u00d7 and memory bandwidth by 4\u00d7; can also accelerate inference 2\u20134\u00d7 on hardware with SIMD int8 support", "Scale $s = (r_{max} - r_{min}) / (2^b - 1)$ where $b$ is bit-width; zero-point $z = -\\text{round}(r_{min} / s)$", "QAT almost always outperforms PTQ for the same target bit-width", "The first and last layers of a network are most sensitive to quantization \u2014 keep them at higher precision when using mixed precision", "Int8 inference on Cortex-M55 (Helium) can achieve 4\u20138\u00d7 speedup over float32 due to vectorized SIMD operations"],
        relatedTopics: [{"level": "level2", "index": 1, "label": "Model Pruning and Sparsity"}, {"level": "level2", "index": 2, "label": "Knowledge Distillation"}, {"level": "level1", "index": 5, "label": "The TinyML Development Workflow"}, {"level": "level2", "index": 7, "label": "Power and Latency Profiling"}],
        resources: [{"title": "Search", "url": "https://www.google.com/search?q=%22quantization%20aware%20training%20TensorFlow%20tutorial%202024%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22post-training%20quantization%20calibration%20dataset%20best%20practices%22"}, {"title": "Paper: \"Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference", "url": "https://www.google.com/search?q=%22Jacob%20et%20al%202018%20quantization%20inference%20integer%20arithmetic%22"}, {"title": "MIT 6.5940 EfficientML lecture on quantization: search", "url": "https://www.google.com/search?q=%22MIT%20EfficientML%20quantization%20lecture%202023%22"}]
    },
    {
        title: "Modell-Pruning und Sparsit\u00e4t",
        content: `<h3>Lesson outline</h3><ul><li>What pruning is: setting weights to exactly zero, reducing effective parameter count</li><li>Magnitude-based pruning: remove weights with |w| &lt; threshold; structured vs. unstructured variants</li><li>Unstructured pruning: individual weights zeroed — high compression ratio but irregular sparsity; requires sparse runtime for speedup</li><li>Structured pruning: remove entire filters/channels/heads — produces dense smaller model; accelerates on any hardware</li><li>Iterative pruning and fine-tuning: prune → fine-tune → prune → fine-tune (Lottery Ticket Hypothesis context)</li><li>Sparsity levels: 50% unstructured sparsity typical; 80–90% possible with QAT + pruning together</li><li>Lottery Ticket Hypothesis: a large network contains a small &quot;winning ticket&quot; subnetwork that can be trained in isolation to similar accuracy</li><li>Pitfall: applying unstructured pruning without a sparse kernel — zeros are still computed; no actual speedup without hardware/software support</li></ul><h3>Key takeaways</h3><ul><li>Structured pruning always gives real speedup; unstructured pruning gives size reduction but needs sparse runtime to gain speed</li><li>The combination of pruning + quantization is multiplicative: 4× from int8 × 2× from 50% structured pruning = 8× total compression</li><li>Always fine-tune after each pruning round; one-shot aggressive pruning collapses accuracy</li><li>Pruning sensitivity varies by layer: early conv layers and the final classifier are most sensitive to pruning</li><li>Iterative gradual pruning (increasing sparsity over training steps) outperforms one-shot pruning</li></ul>`,
        keyPoints: ["Structured pruning always gives real speedup; unstructured pruning gives size reduction but needs sparse runtime to gain speed", "The combination of pruning + quantization is multiplicative: 4\u00d7 from int8 \u00d7 2\u00d7 from 50% structured pruning = 8\u00d7 total compression", "Always fine-tune after each pruning round; one-shot aggressive pruning collapses accuracy", "Pruning sensitivity varies by layer: early conv layers and the final classifier are most sensitive to pruning", "Iterative gradual pruning (increasing sparsity over training steps) outperforms one-shot pruning"],
        relatedTopics: [{"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level2", "index": 2, "label": "Knowledge Distillation"}, {"level": "level2", "index": 3, "label": "Neural Architecture Search for Edge"}],
        resources: [{"title": "Search", "url": "https://www.google.com/search?q=%22neural%20network%20pruning%20Han%20Song%202015%20learning%20both%20weights%20connections%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22lottery%20ticket%20hypothesis%20Frankle%20Carlin%202019%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22structured%20pruning%20filter%20pruning%20convolutional%20neural%20network%22"}, {"title": "MIT 6.5940 EfficientML pruning lecture: search", "url": "https://www.google.com/search?q=%22MIT%20EfficientML%20pruning%20sparsity%20lecture%202023%22"}]
    },
    {
        title: "Wissensdistillation",
        content: `<h3>Lesson outline</h3><ul><li>Core idea: train a small &quot;student&quot; model to mimic a large &quot;teacher&quot; model&#x27;s output distribution, not just hard labels</li><li>Loss function: combined loss $L = \alpha \cdot L_{CE}(\text{student logits}, \text{true labels}) + (1-\alpha) \cdot L_{KL}(\text{soft teacher}, \text{soft student})$ at temperature $T$</li><li>Temperature $T$: softens teacher&#x27;s probability distribution; $T &gt; 1$ reveals inter-class relationships (&quot;dark knowledge&quot;)</li><li>Response-based distillation: match final logits</li><li>Feature-based distillation: match intermediate feature maps; more powerful, more complex to implement</li><li>Relation-based distillation: match relationships between data samples in embedding space</li><li>Self-distillation: a model distills into a smaller version of itself or earlier exits</li><li>Pitfall: setting $\alpha$ and $T$ without tuning — typically $T \in [3, 10]$ and $\alpha \in [0.3, 0.7]$</li></ul><h3>Key takeaways</h3><ul><li>Soft labels from the teacher carry richer gradient signal than one-hot hard labels — the model learns &quot;this image looks a little like a cat&quot; in addition to &quot;it is a dog&quot;</li><li>Distillation is additive with quantization and pruning: distill first, then quantize + prune the student</li><li>Feature-based distillation typically outperforms response-based by 1–3% but requires architectural alignment between teacher and student</li><li>Optimal temperature is task-dependent; start at T=4 and tune</li><li>Distillation can make a 10× smaller model achieve 95–98% of the teacher&#x27;s accuracy</li></ul>`,
        keyPoints: ["Soft labels from the teacher carry richer gradient signal than one-hot hard labels \u2014 the model learns \"this image looks a little like a cat\" in addition to \"it is a dog\"", "Distillation is additive with quantization and pruning: distill first, then quantize + prune the student", "Feature-based distillation typically outperforms response-based by 1\u20133% but requires architectural alignment between teacher and student", "Optimal temperature is task-dependent; start at T=4 and tune", "Distillation can make a 10\u00d7 smaller model achieve 95\u201398% of the teacher's accuracy"],
        relatedTopics: [{"level": "level2", "index": 1, "label": "Model Pruning and Sparsity"}, {"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level2", "index": 3, "label": "Neural Architecture Search for Edge"}],
        resources: [{"title": "Paper: \"Distilling the Knowledge in a Neural Network\" \u2014 Hinton et al. 2015: search", "url": "https://www.google.com/search?q=%22Hinton%20Vinyals%20Dean%20knowledge%20distillation%202015%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22knowledge%20distillation%20survey%20feature-based%20response-based%202023%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22TinyML%20knowledge%20distillation%20MCU%20deployment%20student%20teacher%22"}, {"title": "MIT 6.5940 distillation lecture: search", "url": "https://www.google.com/search?q=%22MIT%20EfficientML%20knowledge%20distillation%202023%22"}]
    },
    {
        title: "Neural Architecture Search f\u00fcr die Edge",
        content: `<h3>Lesson outline</h3><ul><li>What NAS is: automating the search over model architectures to find the best accuracy/efficiency tradeoff for a given hardware target</li><li>Search space: operations (conv types, kernel sizes, skip connections), layer depths, channel widths, input resolutions</li><li>Search strategies: reinforcement learning (original NASNet), evolutionary algorithms, gradient-based (DARTS), one-shot/weight-sharing methods</li><li>Hardware-aware NAS: includes on-device latency or energy as constraints in the objective function, not just FLOPs</li><li>MCUNet: NAS + memory-aware inference scheduling designed explicitly for MCUs; searches jointly over architecture and inference memory layout[^8]</li><li>Proxyless NAS and Once-for-All Network: train one supernet, specialize for many hardware targets without re-training</li><li>Pitfall: using proxy metrics (FLOPs, parameter count) instead of real measured latency — they can differ by 3–5× due to memory bandwidth effects</li></ul><h3>Key takeaways</h3><ul><li>FLOPs/parameter count are poor proxies for MCU latency — always measure on real hardware or an accurate simulator</li><li>Hardware-aware NAS produces Pareto-optimal models for a specific target; a model from NAS for M4F will not be Pareto-optimal on M55</li><li>Once-for-All Networks amortize NAS cost: train once, specialize for any target from the supernet</li><li>NAS output is an architecture specification; the found architecture still requires standard training, quantization, and deployment</li><li>Gradient-based NAS (DARTS) is computationally much cheaper than RL-based NAS but prone to collapse on small search spaces</li></ul>`,
        keyPoints: ["FLOPs/parameter count are poor proxies for MCU latency \u2014 always measure on real hardware or an accurate simulator", "Hardware-aware NAS produces Pareto-optimal models for a specific target; a model from NAS for M4F will not be Pareto-optimal on M55", "Once-for-All Networks amortize NAS cost: train once, specialize for any target from the supernet", "NAS output is an architecture specification; the found architecture still requires standard training, quantization, and deployment", "Gradient-based NAS (DARTS) is computationally much cheaper than RL-based NAS but prone to collapse on small search spaces"],
        relatedTopics: [{"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level2", "index": 1, "label": "Model Pruning and Sparsity"}, {"level": "level3", "index": 2, "label": "Hardware-Software Co-design"}],
        resources: [{"title": "Paper: \"MCUNet: Tiny Deep Learning on IoT Devices\" \u2014 search", "url": "https://www.google.com/search?q=%22MCUNet%20Lin%20et%20al%202020%20NeurIPS%20TinyML%22"}, {"title": "Paper: \"Once-for-All: Train One Network and Specialize it for Efficient Deployment\" \u2014 search", "url": "https://www.google.com/search?q=%22Once-for-All%20Cai%20Han%202020%20ICLR%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22hardware-aware%20neural%20architecture%20search%20edge%20deployment%20survey%202023%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22DARTS%20differentiable%20architecture%20search%20Liu%202019%22"}]
    },
    {
        title: "Audio-Klassifikation und Keyword Spotting",
        content: `<h3>Lesson outline</h3><ul><li>End-to-end pipeline: PDM/I2S microphone → digital decimation filter → PCM audio → STFT → Mel filterbank → log-Mel or MFCC → 2D CNN or 1D CNN</li><li>Keyword spotting (KWS) architecture: small CNN (DS-CNN) on 2D MFCC spectrogram; typical input 49 frames × 10 MFCC coefficients</li><li>Streaming inference: sliding window over continuous audio; keyword detected when output confidence exceeds threshold in N consecutive frames</li><li>Wake-word detection as always-on detector with extremely low power: 2-stage system (tiny always-on detector → larger classifier wake-up)</li><li>Data augmentation for audio: time-shift, background noise mixing, pitch shift, SpecAugment (mask frequency/time bands)</li><li>False positive / false negative tradeoff: ROC curve, operating point selection; for always-on KWS, low FPR is critical</li><li>Pitfall: training without background noise augmentation leads to models that fail on real-world noisy environments</li></ul><h3>Key takeaways</h3><ul><li>DS-CNN on MFCC spectrograms is the de-facto baseline for KWS on MCUs, achieving &gt;96% accuracy in &lt; 80 KB</li><li>Always-on wake-word detection should target &lt; 100 µW; a 2-stage (tiny wake word + larger classifier) system achieves this</li><li>SpecAugment and noise augmentation are the two most impactful data augmentations for KWS robustness</li><li>Operating point (confidence threshold) must be tuned to the application&#x27;s FP/FN cost ratio</li><li>Streaming inference buffer management is a critical implementation detail — plan circular audio buffer in SRAM before model sizing</li></ul>`,
        keyPoints: ["DS-CNN on MFCC spectrograms is the de-facto baseline for KWS on MCUs, achieving >96% accuracy in < 80 KB", "Always-on wake-word detection should target < 100 \u00b5W; a 2-stage (tiny wake word + larger classifier) system achieves this", "SpecAugment and noise augmentation are the two most impactful data augmentations for KWS robustness", "Operating point (confidence threshold) must be tuned to the application's FP/FN cost ratio", "Streaming inference buffer management is a critical implementation detail \u2014 plan circular audio buffer in SRAM before model sizing"],
        relatedTopics: [{"level": "level1", "index": 4, "label": "Sensor Data and Signal Processing Basics"}, {"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level1", "index": 2, "label": "Embedded Systems Constraints"}],
        resources: [{"title": "Paper: \"Hello Edge: Keyword Spotting on Microcontrollers\" \u2014 search", "url": "https://www.google.com/search?q=%22Zhang%20Tang%20Warden%202018%20Hello%20Edge%20keyword%20spotting%20microcontroller%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22SpecAugment%20data%20augmentation%20audio%20Park%202019%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22DS-CNN%20depthwise%20separable%20keyword%20spotting%20MFCC%20benchmark%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22two-stage%20always-on%20wake%20word%20detection%20low%20power%20MCU%22"}]
    },
    {
        title: "Bildklassifikation auf Mikrocontrollern",
        content: `<h3>Lesson outline</h3><ul><li>Camera interfaces on MCUs: DVP parallel, MIPI CSI-2 (higher resolution, higher cost); common sensors for TinyML: QVGA (320×240), QQVGA (160×120)</li><li>Image preprocessing pipeline: capture → resize → normalize → optional grayscale conversion; must fit entirely in SRAM</li><li>MobileNetV1/V2/V3 architecture variants: width multiplier α and resolution multiplier ρ as scaling knobs</li><li>MobileNetV2&#x27;s inverted residuals and linear bottlenecks: expand → depthwise → project pattern</li><li>MCUNet&#x27;s memory scheduling insight: tensor reuse graph ensures peak SRAM (not total) determines feasibility[^8]</li><li>Quantization of image models: uint8 input (0–255 scaled to ), int8 weights, int8 activations[^11]</li><li>Transfer learning for MCU image models: use pretrained MobileNet backbone, replace/retrain classifier head</li><li>Pitfall: resizing images using bilinear interpolation on MCU is compute-heavy; use nearest-neighbor for speed at minor quality cost</li></ul><h3>Key takeaways</h3><ul><li>MobileNetV2 at 0.35 width multiplier and 96×96 input is a practical starting point for MCU image classification under 300 KB Flash</li><li>The width multiplier α scales both MACs (quadratically) and parameters (quadratically); cut α from 1.0 to 0.35 for ~8× parameter reduction</li><li>SRAM peak activation memory is determined by the largest two adjacent layers&#x27; buffers — layer ordering and tiling matter</li><li>Transfer learning from an ImageNet pretrained backbone outperforms training from scratch on small edge datasets (&lt; 5K images)</li><li>Normalize input images with training-set mean and std — keep these constants in firmware</li></ul>`,
        keyPoints: ["MobileNetV2 at 0.35 width multiplier and 96\u00d796 input is a practical starting point for MCU image classification under 300 KB Flash", "The width multiplier \u03b1 scales both MACs (quadratically) and parameters (quadratically); cut \u03b1 from 1.0 to 0.35 for ~8\u00d7 parameter reduction", "SRAM peak activation memory is determined by the largest two adjacent layers' buffers \u2014 layer ordering and tiling matter", "Transfer learning from an ImageNet pretrained backbone outperforms training from scratch on small edge datasets (< 5K images)", "Normalize input images with training-set mean and std \u2014 keep these constants in firmware"],
        relatedTopics: [{"level": "level1", "index": 3, "label": "Machine Learning Foundations for Edge"}, {"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level2", "index": 3, "label": "Neural Architecture Search for Edge"}, {"level": "level3", "index": 0, "label": "Object Detection at the Edge"}],
        resources: [{"title": "Paper: \"MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications\" \u2014 search", "url": "https://www.google.com/search?q=%22Howard%20MobileNet%202017%20efficient%20CNNs%20mobile%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22MobileNetV2%20inverted%20residuals%20linear%20bottlenecks%20Sandler%202018%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22MCUNet%20TinyML%20image%20classification%20microcontroller%20Lin%20NeurIPS%202020%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22transfer%20learning%20TinyML%20image%20classification%20small%20dataset%20MCU%22"}]
    },
    {
        title: "Zeitreihen-Klassifikation und Anomalieerkennung",
        content: `<h3>Lesson outline</h3><ul><li>Time-series tasks in TinyML: activity recognition, predictive maintenance, vibration analysis, ECG anomaly detection</li><li>Classical ML approaches on MCUs: decision trees, random forests, k-NN — viable for simple tasks with low memory[^12]</li><li>Deep learning approaches: 1D-CNN, TCN (Temporal Convolutional Network), lightweight LSTM variants</li><li>Sliding window + feature extraction pipeline for IMU: window size selection (0.5–2 s typical), overlap 50%, time + frequency features</li><li>Anomaly detection approaches: reconstruction error (autoencoder), statistical thresholding (Mahalanobis distance), one-class SVM</li><li>Autoencoder for anomaly: train on normal data only; high reconstruction error → anomaly; MSE threshold set from validation set normal distribution</li><li>Concept drift: distribution of sensor data changes over time (machine wear, temperature changes); detection and adaptation strategies</li><li>Pitfall: evaluating anomaly detection only on known anomalies — unknown anomaly types (open-set) are the real challenge</li></ul><h3>Key takeaways</h3><ul><li>1D-CNNs are preferred over LSTMs for MCU time-series: same receptive field with lower SRAM usage (no hidden state buffer)</li><li>Autoencoder-based anomaly detection requires only normal data for training — ideal for predictive maintenance where failures are rare</li><li>Sliding window overlap (50%) significantly improves classification accuracy at the cost of doubled inference frequency</li><li>Threshold selection for</li><li>Concept drift is structural in long-running deployments — monitor distribution statistics (mean, variance of features) for shift detection</li></ul>`,
        keyPoints: ["1D-CNNs are preferred over LSTMs for MCU time-series: same receptive field with lower SRAM usage (no hidden state buffer)", "Autoencoder-based anomaly detection requires only normal data for training \u2014 ideal for predictive maintenance where failures are rare", "Sliding window overlap (50%) significantly improves classification accuracy at the cost of doubled inference frequency", "Threshold selection for", "Concept drift is structural in long-running deployments \u2014 monitor distribution statistics (mean, variance of features) for shift detection"],
        relatedTopics: [],
        resources: []
    },
    {
        title: "Leistungs- und Latenz-Profiling",
        content: `<h3>Lesson outline</h3><p></p><h3>Key takeaways</h3><p></p>`,
        keyPoints: ["Review the lesson outline and key takeaways above."],
        relatedTopics: [],
        resources: []
    },
]);
