i18n.registerContent('de', 'level1', [
    {
        title: "Was ist TinyML und Edge AI?",
        content: `<h3>Lesson outline</h3><ul><li>Define TinyML: ML inference on ultra-low-power microcontrollers, typically &lt; 1 mW and &lt; 1 MB of memory[^5][^6]</li><li>Distinguish TinyML from Edge AI, Mobile AI, and Cloud AI on a spectrum from µW to kilowatts</li><li>Motivations: latency, bandwidth cost, privacy, offline operation, real-time reaction[^5]</li><li>Key application verticals: predictive maintenance, keyword spotting, gesture recognition, smart agriculture, healthcare wearables[^1]</li><li>The historical arc: from rule-based embedded systems → classical ML on MCUs → deep learning compression</li><li>Pitfall: confusing model accuracy with deployment feasibility — a 95%-accurate cloud model is useless if it needs 4 GB RAM</li></ul><h3>Key takeaways</h3><ul><li>TinyML runs inference (not training) on the device; training always happens offline on more powerful hardware</li><li>The defining constraint triple is: memory (RAM + Flash), compute (FLOPS), and power (mW/µW)</li><li>Edge AI reduces cloud round-trip latency from hundreds of milliseconds to single-digit milliseconds</li><li>Privacy is a structural benefit: raw sensor data never leaves the device</li><li>The field spans hardware, ML algorithms, compilers, and application design — it is inherently cross-disciplinary</li></ul>`,
        keyPoints: ["TinyML runs inference (not training) on the device; training always happens offline on more powerful hardware", "The defining constraint triple is: memory (RAM + Flash), compute (FLOPS), and power (mW/\u00b5W)", "Edge AI reduces cloud round-trip latency from hundreds of milliseconds to single-digit milliseconds", "Privacy is a structural benefit: raw sensor data never leaves the device", "The field spans hardware, ML algorithms, compilers, and application design \u2014 it is inherently cross-disciplinary"],
        relatedTopics: [{"level": "level1", "index": 1, "label": "Microcontroller and Edge Hardware Fundamentals"}, {"level": "level1", "index": 5, "label": "The TinyML Development Workflow"}],
        resources: [{"title": "Book: *TinyML: Machine Learning with TensorFlow Lite on Arduino and Ultra-Low-Power Microcontrollers* \u2014 Pete Warden \\& Daniel Situnayake (O'Reilly, 2019)", "url": "https://www.google.com/search?q=Book%3A%20%2ATinyML%3A%20Machine%20Learning%20with%20TensorFlow%20Lite%20on%20Arduino%20and%20Ultra-Low-Power%20Microcontrollers%2A%20%E2%80%94%20Pete%20Warden%20%5C%26%20Daniel%20Situnayake%20%28O%27Reilly%2C%202019%29"}, {"title": "Harvard edX series: search", "url": "https://www.google.com/search?q=%22Fundamentals%20of%20TinyML%20edX%20Harvard%20Professional%20Certificate%22"}, {"title": "Paper: \"TinyML for Ubiquitous Edge AI\" \u2014 search", "url": "https://www.google.com/search?q=arxiv%202102.01255%20TinyML%20ubiquitous%20edge%20AI"}, {"title": "Survey: \"A Machine Learning-oriented Survey on Tiny Machine Learning\" \u2014 search", "url": "https://www.google.com/search?q=arxiv%202309.11932%20TinyML%20survey"}]
    },
    {
        title: "Mikrocontroller- und Edge-Hardware-Grundlagen",
        content: `<h3>Lesson outline</h3><ul><li>MCU anatomy: CPU core (ARM Cortex-M series: M0+, M4, M7, M33, M55), SRAM, Flash, peripherals</li><li>Compare MCU tiers: Cortex-M0+ (≈16 KB RAM) → M4F (≈256 KB, DSP/FPU) → M55 (Helium SIMD)[^7]</li><li>Microprocessors (MPUs) vs. microcontrollers: i.MX RT, Raspberry Pi, NVIDIA Jetson Nano — more memory, higher power[^7]</li><li>Dedicated neural accelerators: edge TPUs (e.g., Coral), NPUs embedded in SoCs, FPGAs for custom dataflows[^7]</li><li>Memory hierarchy: SRAM (fast, tiny) → QSPI Flash (slower, larger) → external PSRAM (latency penalty)</li><li>Peripherals relevant to AI: ADC, I2S/PDM for audio, camera interfaces (DVP/MIPI-CSI), accelerometers (SPI/I2C)</li><li>Pitfall: quoting MCU clock speed (e.g., 480 MHz) without noting that most MCUs have no out-of-order execution or cache the size of an L1 cache on a PC</li></ul><h3>Key takeaways</h3><ul><li>RAM (SRAM) is the most critical bottleneck: it holds activation buffers at runtime; Flash holds model weights</li><li>Cortex-M4 with FPU is the most common starting point for TinyML workloads</li><li>An NPU or edge TPU can accelerate inference by 10–100× vs. CPU alone while cutting power</li><li>FPGAs offer the highest flexibility and lowest latency but require HDL expertise</li><li>Match hardware tier to workload: simple classifiers on M0+, CNNs on M4/M55, video on MPUs</li></ul>`,
        keyPoints: ["RAM (SRAM) is the most critical bottleneck: it holds activation buffers at runtime; Flash holds model weights", "Cortex-M4 with FPU is the most common starting point for TinyML workloads", "An NPU or edge TPU can accelerate inference by 10\u2013100\u00d7 vs. CPU alone while cutting power", "FPGAs offer the highest flexibility and lowest latency but require HDL expertise", "Match hardware tier to workload: simple classifiers on M0+, CNNs on M4/M55, video on MPUs"],
        relatedTopics: [{"level": "level1", "index": 0, "label": "What Is TinyML and Edge AI"}, {"level": "level1", "index": 2, "label": "Embedded Systems Constraints"}, {"level": "level3", "index": 2, "label": "Hardware-Software Co-design"}],
        resources: [{"title": "ARM Cortex-M Series documentation: search", "url": "https://www.google.com/search?q=%22ARM%20Cortex-M%20processor%20series%20developer%20guide%22"}, {"title": "Book: *Making Embedded Systems* \u2014 Elecia White (O'Reilly)", "url": "https://www.google.com/search?q=Book%3A%20%2AMaking%20Embedded%20Systems%2A%20%E2%80%94%20Elecia%20White%20%28O%27Reilly%29"}, {"title": "Search", "url": "https://www.google.com/search?q=%22NVIDIA%20Jetson%20Nano%20vs%20Coral%20Edge%20TPU%20benchmark%20comparison%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22MCUNet%20TinyML%20microcontroller%20neural%20network%20MIT%20Han%20Song%22"}]
    },
    {
        title: "Eingebettete Systeme: Randbedingungen",
        content: `<h3>Lesson outline</h3><ul><li>The constraint triad in depth: memory (SRAM/Flash), compute (MACs/s), and power (active/sleep current × duty cycle)</li><li>Memory budget breakdown: model weights (static, in Flash), activation buffers (dynamic, in SRAM), intermediate buffers, runtime stack</li><li>Compute cost of neural network operations: multiplications-accumulations (MACs) as the primary metric; latency = MACs ÷ effective MAC throughput</li><li>Power modes: active inference, sleep, deep sleep; duty cycling patterns for always-on detection</li><li>Energy vs. power: a 10 mW device drawing 1 mW average lives for 1000 hours on a 1 Wh battery (basic estimate)</li><li>Thermal constraints in sealed enclosures</li><li>Pitfall: forgetting that preprocessing (FFT, normalization) and post-processing also consume RAM and cycles, not just the neural network</li></ul><h3>Key takeaways</h3><ul><li>SRAM usage is dominated by activations, not weights — this is the opposite of desktop ML intuitions</li><li>MACs are a hardware-independent proxy for inference time; real latency depends on memory bandwidth and pipeline efficiency</li><li>Power = current × voltage; energy = power × time; minimize both active duration and idle current</li><li>Duty cycling (wake → sense → infer → sleep) is the primary battery-life strategy</li><li>Always account for the full pipeline budget, not just the model&#x27;s isolated cost</li></ul>`,
        keyPoints: ["SRAM usage is dominated by activations, not weights \u2014 this is the opposite of desktop ML intuitions", "MACs are a hardware-independent proxy for inference time; real latency depends on memory bandwidth and pipeline efficiency", "Power = current \u00d7 voltage; energy = power \u00d7 time; minimize both active duration and idle current", "Duty cycling (wake \u2192 sense \u2192 infer \u2192 sleep) is the primary battery-life strategy", "Always account for the full pipeline budget, not just the model's isolated cost"],
        relatedTopics: [{"level": "level1", "index": 1, "label": "Microcontroller and Edge Hardware Fundamentals"}, {"level": "level2", "index": 7, "label": "Power and Latency Profiling"}, {"level": "level2", "index": 0, "label": "Model Quantization"}],
        resources: [{"title": "Book: *Designing Embedded Systems* \u2014 John Catsoulis (O'Reilly)", "url": "https://www.google.com/search?q=Book%3A%20%2ADesigning%20Embedded%20Systems%2A%20%E2%80%94%20John%20Catsoulis%20%28O%27Reilly%29"}, {"title": "Search", "url": "https://www.google.com/search?q=%22TinyML%20memory%20optimization%20activation%20buffer%20reuse%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22embedded%20AI%20power%20consumption%20duty%20cycle%20MCU%20deep%20sleep%22"}, {"title": "MIT 6.5940 EfficientML course: search", "url": "https://www.google.com/search?q=%22MIT%20EfficientML%206.5940%20TinyML%20lecture%20notes%22"}]
    },
    {
        title: "Machine-Learning-Grundlagen f\u00fcr die Edge",
        content: `<h3>Lesson outline</h3><ul><li>Brief review of supervised learning: input → model → prediction → loss → gradient descent (not the full ML curriculum, just enough to contextualize edge constraints)</li><li>Neural network layer types relevant to TinyML: Dense/Fully-Connected, Conv1D, Conv2D, Depthwise Separable Convolution, BatchNorm, ReLU</li><li>Why depth-wise separable convolutions are preferred on edge: parameter count and MAC reduction vs. standard convolution</li><li>Depthwise separable: standard Conv2D MACs = $D_K^2 \cdot M \cdot N \cdot D_F^2$, depthwise = $D_K^2 \cdot M \cdot D_F^2 + M \cdot N \cdot D_F^2$; ratio ≈ $\frac{1}{N} + \frac{1}{D_K^2}$</li><li>Inference vs. training: why backprop is infeasible on MCUs</li><li>Model size vs. accuracy tradeoffs: the Pareto curve of accuracy vs. parameter count</li><li>Pitfall: using BatchNorm layers at inference time without folding — they add compute; fold BN into preceding conv weights before deployment</li></ul><h3>Key takeaways</h3><ul><li>Depthwise separable convolutions reduce MACs by ~8–9× vs. standard Conv2D with minimal accuracy loss</li><li>At inference, BatchNorm can be mathematically folded into the preceding layer&#x27;s weights and biases — this must be done before deployment</li><li>ReLU6 (clamped at 6) is preferred on edge because it restricts activation ranges, improving fixed-point quantization</li><li>The number of parameters ≠ inference cost; activation memory (feature maps) is often the binding constraint</li><li>Classification, regression, and anomaly detection are the three most common TinyML task types</li></ul>`,
        keyPoints: ["Depthwise separable convolutions reduce MACs by ~8\u20139\u00d7 vs. standard Conv2D with minimal accuracy loss", "At inference, BatchNorm can be mathematically folded into the preceding layer's weights and biases \u2014 this must be done before deployment", "ReLU6 (clamped at 6) is preferred on edge because it restricts activation ranges, improving fixed-point quantization", "The number of parameters \u2260 inference cost; activation memory (feature maps) is often the binding constraint", "Classification, regression, and anomaly detection are the three most common TinyML task types"],
        relatedTopics: [{"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level2", "index": 3, "label": "Neural Architecture Search for Edge"}, {"level": "level2", "index": 4, "label": "Audio Classification and Keyword Spotting"}],
        resources: [{"title": "Book: *Deep Learning* \u2014 Goodfellow, Bengio, Courville (free online at", "url": "https://www.google.com/search?q=deeplearningbook.org"}, {"title": "Search", "url": "https://www.google.com/search?q=%22depthwise%20separable%20convolution%20MobileNet%20Howard%202017%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22BatchNorm%20folding%20inference%20TinyML%20optimization%22"}, {"title": "MIT 6.S191 Introduction to Deep Learning: search", "url": "https://www.google.com/search?q=%22MIT%206.S191%20deep%20learning%202024%22"}]
    },
    {
        title: "Sensordaten und Signalverarbeitung (Basics)",
        content: `<h3>Lesson outline</h3><ul><li>Sensor modalities in TinyML: IMU (accelerometer/gyro), microphone (PDM/I2S), temperature, pressure, image (camera modules), time-of-flight</li><li>Sampling theorem (Nyquist): sample rate ≥ 2 × highest frequency of interest; aliasing artifact when violated</li><li>Windowing: fixed-length frame extraction, hop size, overlap; stationarity assumption in short frames</li><li>Feature engineering for audio: Short-Time Fourier Transform (STFT), Mel Filterbank, Mel-Frequency Cepstral Coefficients (MFCCs)</li><li>Feature engineering for IMU: time-domain features (mean, RMS, peak, zero-crossing rate), frequency-domain (FFT magnitude), statistical features</li><li>Normalization: per-sample z-score, min-max, or dataset-level standardization — which to use when</li><li>Pitfall: applying dataset-level normalization statistics at inference without storing them — the MCU must have mean/std constants baked in at compile time</li></ul><h3>Key takeaways</h3><ul><li>Always set sample rate to at least 2× your maximum frequency of interest; common choices: 16 kHz for speech, 100–400 Hz for IMU gesture</li><li>MFCCs compress an audio spectrum into 13–40 compact coefficients mimicking the human auditory system — the standard audio feature for TinyML</li><li>Windowing choices (Hann, Hamming) reduce spectral leakage in STFT — prefer Hann for most audio applications</li><li>Normalization statistics computed on training data must be hard-coded constants at deployment, not recomputed on the device</li><li>Preprocessing is part of the inference pipeline and must fit within the memory and latency budget</li></ul>`,
        keyPoints: ["Always set sample rate to at least 2\u00d7 your maximum frequency of interest; common choices: 16 kHz for speech, 100\u2013400 Hz for IMU gesture", "MFCCs compress an audio spectrum into 13\u201340 compact coefficients mimicking the human auditory system \u2014 the standard audio feature for TinyML", "Windowing choices (Hann, Hamming) reduce spectral leakage in STFT \u2014 prefer Hann for most audio applications", "Normalization statistics computed on training data must be hard-coded constants at deployment, not recomputed on the device", "Preprocessing is part of the inference pipeline and must fit within the memory and latency budget"],
        relatedTopics: [{"level": "level2", "index": 4, "label": "Audio Classification and Keyword Spotting"}, {"level": "level2", "index": 6, "label": "Time-Series Classification and Anomaly Detection"}, {"level": "level1", "index": 2, "label": "Embedded Systems Constraints"}],
        resources: [{"title": "Search", "url": "https://www.google.com/search?q=%22MFCC%20tutorial%20speech%20processing%20Python%20librosa%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22Nyquist%20sampling%20theorem%20DSP%20microcontroller%20application%22"}, {"title": "Book: *Speech and Language Processing* \u2014 Jurafsky \\& Martin Chapter 16 (free at", "url": "https://www.google.com/search?q=web.stanford.edu/~jurafsky/slp3/"}, {"title": "Search", "url": "https://www.google.com/search?q=%22IMU%20feature%20extraction%20TinyML%20gesture%20recognition%22"}]
    },
    {
        title: "Der TinyML-Entwicklungsworkflow",
        content: `<h3>Lesson outline</h3><ul><li>End-to-end pipeline: data collection → labeling → preprocessing → model training → evaluation → optimization → conversion → deployment → monitoring</li><li>Offline training environment: Python, standard ML framework (TensorFlow, PyTorch), GPU/CPU workstation or cloud</li><li>Conversion step: trained floating-point model → hardware-optimized format (e.g., TFLite Flatbuffer, ONNX + runtime)</li><li>On-device runtime: interpreter that reads the converted model and executes layer-by-layer using MCU-optimized kernels</li><li>Flash programming: compiled firmware = runtime + model weights + application code, deployed as a single binary</li><li>Feedback loop: captured edge data → retrain → re-deploy; concept drift over time</li><li>Pitfall: treating conversion as lossless — quantization and operator support gaps can reduce accuracy and require re-evaluation after conversion</li></ul><h3>Key takeaways</h3><ul><li>Training and deployment are separate phases executed on different machines; the conversion step bridges them</li><li>The on-device runtime must support every layer type used in the model — unsupported ops cause deployment failures</li><li>Measure model accuracy again after conversion; quantization-induced accuracy loss can be 1–5% and must be validated</li><li>The full binary (runtime + model) must fit in Flash; plan the Flash budget before designing the model</li><li>Data collection from the target hardware itself (with the target sensors) produces the most deployment-accurate training data</li></ul>`,
        keyPoints: ["Training and deployment are separate phases executed on different machines; the conversion step bridges them", "The on-device runtime must support every layer type used in the model \u2014 unsupported ops cause deployment failures", "Measure model accuracy again after conversion; quantization-induced accuracy loss can be 1\u20135% and must be validated", "The full binary (runtime + model) must fit in Flash; plan the Flash budget before designing the model", "Data collection from the target hardware itself (with the target sensors) produces the most deployment-accurate training data"],
        relatedTopics: [{"level": "level1", "index": 0, "label": "What Is TinyML and Edge AI"}, {"level": "level2", "index": 0, "label": "Model Quantization"}, {"level": "level3", "index": 3, "label": "Edge MLOps and Model Lifecycle"}],
        resources: [{"title": "Search", "url": "https://www.google.com/search?q=%22TensorFlow%20Lite%20model%20conversion%20quantization%20tutorial%22"}, {"title": "Search", "url": "https://www.google.com/search?q=%22ONNX%20Runtime%20edge%20deployment%20microcontroller%22"}, {"title": "Harvard TinyML Professional Certificate", "url": "https://www.google.com/search?q=tinymlx.github.io/courses/"}, {"title": "Search", "url": "https://www.google.com/search?q=%22Edge%20Impulse%20MLOps%20TinyML%20workflow%20end%20to%20end%22"}]
    },
]);
