i18n.registerContent('en', 'scenarios', [
    { level: 'level1', topicIndex: 0, title: 'Rotated vendor images', description: 'Images look rotated 90° but arrays are 1080×1920. Most likely cause?', choices: [{ text: 'Non-standard color space', correct: false, xp: 0 }, { text: 'EXIF orientation ignored by the loader', correct: true, xp: 15 }, { text: 'Width and height swapped in the array', correct: false, xp: 0 }, { text: 'The model needs extra preprocessing layers', correct: false, xp: 0 }], explanation: 'EXIF tags tell viewers to rotate; many loaders skip them so arrays look sideways.' },
    { level: 'level1', topicIndex: 1, title: 'Blobs in a noisy mask', description: 'Find large blobs in a noisy binary mask before further steps. Best classical approach?', choices: [{ text: 'Sobel gradient filter', correct: false, xp: 0 }, { text: 'Unsharp mask', correct: false, xp: 0 }, { text: 'Morphological opening then connected components', correct: true, xp: 15 }, { text: 'Histogram equalization', correct: false, xp: 0 }], explanation: 'Opening removes speckle; CC labeling extracts regions.' },
    { level: 'level1', topicIndex: 2, title: 'Embedded panorama', description: 'Panorama stitching on embedded CPU, no GPU. Most practical?', choices: [{ text: 'End-to-end CNN keypoints', correct: false, xp: 0 }, { text: 'Classical SIFT-like features and matching', correct: true, xp: 15 }, { text: 'Vision transformer correspondences', correct: false, xp: 0 }, { text: 'Dense optical flow at full resolution', correct: false, xp: 0 }], explanation: 'Classical features are light, deterministic, and well understood on edge hardware.' },
    { level: 'level1', topicIndex: 3, title: 'Train vs validation gap', description: 'Near-perfect train accuracy in 5 epochs but ~60% validation on a large set. Try first?', choices: [{ text: 'Add more layers', correct: false, xp: 0 }, { text: 'Reduce learning rate only', correct: false, xp: 0 }, { text: 'Stronger regularization and/or augmentation', correct: true, xp: 15 }, { text: 'Switch to a regression loss', correct: false, xp: 0 }], explanation: 'Large train–val gap signals overfitting; regularize before scaling capacity.' },
    { level: 'level1', topicIndex: 4, title: 'Skin-lesion augmentation', description: 'Flips exist; colleague wants extreme hue shifts (±180°). What do you do?', choices: [{ text: 'Apply freely — hue jitter always helps', correct: false, xp: 0 }, { text: 'Use only at test time', correct: false, xp: 0 }, { text: 'Test carefully — extreme hue may erase clinical color cues', correct: true, xp: 15 }, { text: 'Replace everything with RandAugment blindly', correct: false, xp: 0 }], explanation: 'Domain knowledge: color carries diagnostic signal; validate augments empirically.' },
    { level: 'level1', topicIndex: 5, title: 'Mobile 1000-way classifier', description: '224×224, 1000 classes on a phone. Most important design principle?', choices: [{ text: 'Maximize depth regardless of cost', correct: false, xp: 0 }, { text: 'Replace all pooling with strided conv only', correct: false, xp: 0 }, { text: 'Depthwise separable convs + global average pooling', correct: true, xp: 15 }, { text: 'Double early-layer filters', correct: false, xp: 0 }], explanation: 'Separable convs and GAP cut parameters and latency for edge deployment.' },
    { level: 'level1', topicIndex: 6, title: 'Fraud detector accuracy', description: '98% normal, 2% fraud; model shows 98.5% accuracy. Deploy?', choices: [{ text: 'Yes — accuracy is excellent', correct: false, xp: 0 }, { text: 'Yes with weekly monitoring only', correct: false, xp: 0 }, { text: 'No — check recall/precision on the fraud class first', correct: true, xp: 15 }, { text: 'No — below 99% is never enough', correct: false, xp: 0 }], explanation: 'Always-negative baseline can score ~98%; rare-class metrics decide usefulness.' },

    { level: 'level2', topicIndex: 0, title: 'RGB + infrared backbone', description: 'Pre-trained checkpoint must load; inputs have 4 channels (RGB+IR). Best approach?', choices: [{ text: 'Drop IR and use 3-channel weights', correct: false, xp: 0 }, { text: 'Adapt first conv to 4 channels, then fine-tune', correct: true, xp: 15 }, { text: 'Retrain entire net from scratch', correct: false, xp: 0 }, { text: 'Split into two 2-channel inputs', correct: false, xp: 0 }], explanation: 'Only the stem depends on input depth; initialize the new channel sensibly and fine-tune.' },
    { level: 'level2', topicIndex: 1, title: '500 chest X-rays', description: 'Pneumonia detection; ImageNet backbone available. Strongest path?', choices: [{ text: 'Train from scratch', correct: false, xp: 0 }, { text: 'ImageNet, freeze backbone, train head only', correct: false, xp: 0 }, { text: 'ImageNet, unfreeze all with small LR', correct: false, xp: 0 }, { text: 'Medical-domain pre-training + differential fine-tuning if available', correct: true, xp: 15 }], explanation: 'Domain-matched pre-training plus careful fine-tuning beats tiny-data from-scratch training.' },
    { level: 'level2', topicIndex: 2, title: 'Server + mobile classifiers', description: 'Need best server accuracy and a light mobile variant. Most efficient overall?', choices: [{ text: 'Two models trained independently from scratch', correct: false, xp: 0 }, { text: 'Train large model, distill to small with soft targets', correct: true, xp: 15 }, { text: 'Only train the small model on all data', correct: false, xp: 0 }, { text: 'Prune the large model only', correct: false, xp: 0 }], explanation: 'Distillation transfers rich dark knowledge to the student.' },
    { level: 'level2', topicIndex: 3, title: 'Dense fish counting', description: 'Count fish in dense underwater video in real time (30 fps). Best fit?', choices: [{ text: 'Two-stage detector for max accuracy', correct: false, xp: 0 }, { text: 'One-stage anchor-free detector + soft-NMS for crowds', correct: true, xp: 15 }, { text: 'Classifier on sliding crops only', correct: false, xp: 0 }, { text: 'Semantic segmentation only', correct: false, xp: 0 }], explanation: 'Speed + anchor-free + softer suppression handles density and aspect variation.' },
    { level: 'level2', topicIndex: 4, title: 'Highway signs vs pedestrians', description: 'Single-scale detector misses small signs in 1280×720. Most targeted fix?', choices: [{ text: 'Double input resolution always', correct: false, xp: 0 }, { text: 'Add an FPN for multi-scale features', correct: true, xp: 15 }, { text: 'Switch anchor-free only', correct: false, xp: 0 }, { text: 'Shallower backbone', correct: false, xp: 0 }], explanation: 'FPN gives high-res feature levels for small objects without full 2× input cost.' },
    { level: 'level2', topicIndex: 5, title: 'Rotated document text', description: 'Text at 30°–45°; axis-aligned boxes waste background. Prefer?', choices: [{ text: 'Standard YLO + aggressive NMS', correct: false, xp: 0 }, { text: 'DETR with default boxes', correct: false, xp: 0 }, { text: 'Rotated box detector (x, y, w, h, θ)', correct: true, xp: 15 }, { text: 'Semantic seg + axis box fitting', correct: false, xp: 0 }], explanation: 'Oriented boxes tighten crops for OCR on skewed scans.' },
    { level: 'level2', topicIndex: 6, title: 'Real-time lane segmentation', description: 'DeepLabv3+ large backbone: 12 fps; need 30 fps on Jetson. Targeted move?', choices: [{ text: 'Switch to instance segmentation', correct: false, xp: 0 }, { text: 'Lighter encoder + simpler decoder', correct: true, xp: 15 }, { text: 'Resize inputs to 32×32', correct: false, xp: 0 }, { text: 'Remove all skip connections', correct: false, xp: 0 }], explanation: 'BiSeNet-style light encoders and simple decoders are standard for real-time lanes.' },
    { level: 'level2', topicIndex: 7, title: 'Grasp on a cluttered belt', description: 'Need exact per-object pixel boundaries for grasping, not just boxes.', choices: [{ text: 'Semantic seg + heuristic split', correct: false, xp: 0 }, { text: 'Detection with boxes only', correct: false, xp: 0 }, { text: 'Instance segmentation masks', correct: true, xp: 15 }, { text: 'Monocular depth only', correct: false, xp: 0 }], explanation: 'Instance masks separate touching objects for contact planning.' },
    { level: 'level2', topicIndex: 8, title: 'Drivable + instances', description: 'Road/sidewalk stuff plus distinct pedestrians and vehicles. Output format?', choices: [{ text: 'Semantic only', correct: false, xp: 0 }, { text: 'Detection only', correct: false, xp: 0 }, { text: 'Instance only', correct: false, xp: 0 }, { text: 'Panoptic segmentation', correct: true, xp: 15 }], explanation: 'Panoptic unifies stuff (regions) and things (instances) in one label map.' },

    { level: 'level3', topicIndex: 0, title: 'Dense prediction at 500k images', description: 'CNN 78% mIoU; ViT-B on same data 75%. Next step?', choices: [{ text: 'Scale to ViT-H blindly', correct: false, xp: 0 }, { text: 'Try Swin — hierarchical, more data-efficient for dense tasks', correct: true, xp: 15 }, { text: 'Claim CNNs always win; stop', correct: false, xp: 0 }, { text: 'Train ViT-B from scratch on 500k', correct: false, xp: 0 }], explanation: 'Swin provides pyramid features and local inductive bias suited to segmentation.' },
    { level: 'level3', topicIndex: 1, title: '2M unlabeled products', description: '5k labeled SKUs; fine-grained product ID. Best strategy?', choices: [{ text: 'Supervised CNN on 5k only', correct: false, xp: 0 }, { text: 'MAE pre-train on 2M, then fine-tune on labels', correct: true, xp: 15 }, { text: 'Classical descriptors on unlabeled pool', correct: false, xp: 0 }, { text: 'k-means cluster IDs as labels', correct: false, xp: 0 }], explanation: 'Self-supervised pre-training leverages unlabeled scale before small-label fine-tune.' },
    { level: 'level3', topicIndex: 2, title: 'Motion without full RAFT', description: 'Action model needs motion cues; full RAFT too heavy at 30 fps.', choices: [{ text: 'Raw frame differences', correct: false, xp: 0 }, { text: 'Light flow or subsampled flow + interpolation', correct: true, xp: 15 }, { text: 'Drop motion; RGB only', correct: false, xp: 0 }, { text: 'RAFT every 10th frame, no interpolation', correct: false, xp: 0 }], explanation: 'Cheap flow or temporal subsampling preserves motion while saving compute.' },
    { level: 'level3', topicIndex: 3, title: 'Surgical incision in long video', description: '3-hour video; find a specific incision; accuracy critical, not real-time.', choices: [{ text: 'Classify every 30th frame only', correct: false, xp: 0 }, { text: 'Coarse scene filter + temporal localization with a strong video model', correct: true, xp: 15 }, { text: 'Optical flow without appearance', correct: false, xp: 0 }, { text: 'Audio events only', correct: false, xp: 0 }], explanation: 'Narrow temporal search then precise temporal modeling balances cost and recall.' },
    { level: 'level3', topicIndex: 4, title: 'Warehouse robot depth', description: 'One sensor budget; need reliable metric depth for navigation.', choices: [{ text: 'Monocular self-supervised depth only', correct: false, xp: 0 }, { text: 'Stereo RGB + learned matching', correct: true, xp: 15 }, { text: '2-D LiDAR only', correct: false, xp: 0 }, { text: 'Fisheye RGB without depth', correct: false, xp: 0 }], explanation: 'Stereo gives metric depth at high rate and moderate cost; monocular stays scale-ambiguous.' },
    { level: 'level3', topicIndex: 5, title: 'Rare defect synthesis', description: '200 real defect photos; need synthetic training variety.', choices: [{ text: 'Train DDPM from scratch on 200', correct: false, xp: 0 }, { text: 'Fine-tune a latent diffusion model (DreamBooth/LoRA)', correct: true, xp: 15 }, { text: 'VAE interpolate between 200 samples only', correct: false, xp: 0 }, { text: 'Nearest-neighbor augmentation only', correct: false, xp: 0 }], explanation: 'Adapt a strong pre-trained generative model; tiny data cannot train diffusion from zero.' },
    { level: 'level3', topicIndex: 6, title: 'VFX sparse views', description: 'Photoreal novel views of a real set; offline OK; quality paramount.', choices: [{ text: 'Classic mesh photogrammetry only', correct: false, xp: 0 }, { text: 'Modern NeRF family (e.g., Instant-NGP / Zip-NeRF)', correct: true, xp: 15 }, { text: '3DGS only, never NeRF', correct: false, xp: 0 }, { text: 'Single-image depth warp', correct: false, xp: 0 }], explanation: 'Implicit radiance fields handle complex appearance with calibrated multi-view captures.' },
    { level: 'level3', topicIndex: 7, title: 'MCU vision (512KB flash)', description: 'No FPU; classify on microcontroller. Combine what?', choices: [{ text: 'ResNet-50 FP32', correct: false, xp: 0 }, { text: 'Depthwise-separable CNN + INT8 quantization', correct: true, xp: 15 }, { text: 'Unstructured-pruned ResNet-50', correct: false, xp: 0 }, { text: '8-head ViT FP32', correct: false, xp: 0 }], explanation: 'Tiny integer-friendly backbones match MCU constraints; unstructured sparsity rarely helps without HW.' },

    { level: 'level4', topicIndex: 0, title: 'Defect Q&A in free text', description: 'Users upload defect photos and ask open-ended “why does it look like this?”', choices: [{ text: 'CLIP zero-shot with fixed labels', correct: false, xp: 0 }, { text: 'Instruction-tuned LVLM on domain images', correct: true, xp: 15 }, { text: 'Legacy VQA on general benchmarks only', correct: false, xp: 0 }, { text: 'Detector + static lookup table', correct: false, xp: 0 }], explanation: 'Open-ended reasoning needs generative multimodal models, not fixed vocab classifiers.' },
    { level: 'level4', topicIndex: 1, title: 'Sofa in new scenes', description: '50 sofa photos; users prompt “sofa in modern living room.” Practical pipeline?', choices: [{ text: 'GAN from scratch on 50 images', correct: false, xp: 0 }, { text: 'Frozen diffusion + IP-Adapter (or similar) + text scene prompt', correct: true, xp: 15 }, { text: 'Classical cut-and-paste only', correct: false, xp: 0 }, { text: 'Full diffusion fine-tune on 50 pairs standard loss', correct: false, xp: 0 }], explanation: 'Condition appearance without retraining the whole U-Net from dozens of images.' },
    { level: 'level4', topicIndex: 2, title: 'Face accuracy vs subgroup', description: '99.2% benchmark accuracy; 3× false accepts on darker skin. Ship?', choices: [{ text: 'Ship now; overall accuracy only matters', correct: false, xp: 0 }, { text: 'Delay; balance/retrain, stratified goals, document in model card', correct: true, xp: 15 }, { text: 'Per-group thresholds only, no other changes', correct: false, xp: 0 }, { text: 'Drop demographic fields from training to “remove bias”', correct: false, xp: 0 }], explanation: 'Fairness gaps need mitigation and disclosure, not ignoring subgroup failure modes.' },
    { level: 'level4', topicIndex: 3, title: 'Sudden false negatives', description: 'Vision defect model degrades; no code changes for months.', choices: [{ text: 'Silent weight corruption', correct: false, xp: 0 }, { text: 'Input distribution shift (camera/lighting) — check input drift monitors', correct: true, xp: 15 }, { text: 'GPU hardware faults', correct: false, xp: 0 }, { text: 'Training labels silently corrupted in prod', correct: false, xp: 0 }], explanation: 'Production CV often drifts when sensors or environment change despite frozen code.' },
    { level: 'level4', topicIndex: 4, title: 'Recycling sorter capstone', description: '2 items/s, 24/7, one edge GPU, >97% per class including rare contaminants.', choices: [{ text: 'CLIP zero-shot only', correct: false, xp: 0 }, { text: 'Synthetic-only ResNet-50, no monitoring', correct: false, xp: 0 }, { text: 'Real belt data, efficient backbone, drift monitoring, hard-negative loop', correct: true, xp: 15 }, { text: 'Panoptic segmentation for sorting', correct: false, xp: 0 }], explanation: 'Production sorting needs domain data, efficiency, and continuous monitoring/retrain.' }
]);
