i18n.registerContent('de', 'scenarios', [
    { level: 'level1', topicIndex: 0, title: 'Gedrehte Lieferantenbilder', description: 'Bilder wirken um 90° gedreht, Arrays sind aber 1080×1920. Wahrscheinlichste Ursache?', choices: [{ text: 'Nicht-standardisierte Farbräume', correct: false, xp: 0 }, { text: 'EXIF-Orientierung wird vom Loader ignoriert', correct: true, xp: 15 }, { text: 'Breite und Höhe im Array vertauscht', correct: false, xp: 0 }, { text: 'Das Modell braucht zusätzliche Vorverarbeitungsschichten', correct: false, xp: 0 }], explanation: 'EXIF-Tags steuern die Anzeige-Rotation; viele Loader ignorieren sie.' },
    { level: 'level1', topicIndex: 1, title: 'Blob in einer verrauschten Maske', description: 'Große Blobs in einer verrauschten Binärmaske finden. Bestes klassisches Vorgehen?', choices: [{ text: 'Sobel-Gradient', correct: false, xp: 0 }, { text: 'Unsharp Mask', correct: false, xp: 0 }, { text: 'Morphologisches Opening, dann zusammenhängende Komponenten', correct: true, xp: 15 }, { text: 'Histogrammausgleich', correct: false, xp: 0 }], explanation: 'Opening entfernt Kleckse; CC-Labeling extrahiert Regionen.' },
    { level: 'level1', topicIndex: 2, title: 'Embedded-Panorama', description: 'Panorama-Stitching auf eingebetteter CPU ohne GPU. Praktischste Lösung?', choices: [{ text: 'End-to-End-CNN-Keypoints', correct: false, xp: 0 }, { text: 'Klassische SIFT-ähnliche Merkmale und Matching', correct: true, xp: 15 }, { text: 'Vision-Transformer-Korrespondenzen', correct: false, xp: 0 }, { text: 'Dichter optischer Fluss in voller Auflösung', correct: false, xp: 0 }], explanation: 'Klassische Merkmale sind leicht, deterministisch und auf Edge-Hardware üblich.' },
    { level: 'level1', topicIndex: 3, title: 'Train–Valid-Lücke', description: 'Fast perfektes Training, ~60 % Validierung auf großem Datensatz. Zuerst?', choices: [{ text: 'Mehr Schichten', correct: false, xp: 0 }, { text: 'Nur Lernrate senken', correct: false, xp: 0 }, { text: 'Stärkere Regularisierung und/oder Augmentation', correct: true, xp: 15 }, { text: 'Auf Regressionsverlust wechseln', correct: false, xp: 0 }], explanation: 'Große Lücke deutet auf Überanpassung — vor Kapazität regularisieren.' },
    { level: 'level1', topicIndex: 4, title: 'Hautläsion-Augmentation', description: 'Flips vorhanden; Kollege will extreme Farbtonverschiebungen (±180°).', choices: [{ text: 'Frei anwenden — hilft immer', correct: false, xp: 0 }, { text: 'Nur zur Testzeit', correct: false, xp: 0 }, { text: 'Vorsichtig testen — extreme Hue kann klinische Farbsignale zerstören', correct: true, xp: 15 }, { text: 'Alles blind durch RandAugment ersetzen', correct: false, xp: 0 }], explanation: 'Domänenwissen: Farbe trägt Diagnose; empirisch prüfen.' },
    { level: 'level1', topicIndex: 5, title: 'Mobile 1000-Klassen', description: '224×224, 1000 Klassen auf dem Handy. Wichtigstes Prinzip?', choices: [{ text: 'Maximale Tiefe um jeden Preis', correct: false, xp: 0 }, { text: 'Alle Pools durch gestrichelte Conv ersetzen', correct: false, xp: 0 }, { text: 'Tiefen-separable Faltungen + Global Average Pooling', correct: true, xp: 15 }, { text: 'Frühe Filter verdoppeln', correct: false, xp: 0 }], explanation: 'Separable Convs und GAP senken Parameter und Latenz.' },
    { level: 'level1', topicIndex: 6, title: 'Betrugsdetektor-Genauigkeit', description: '98 % normal, 2 % Betrug; Modell 98,5 % Genauigkeit. Deploy?', choices: [{ text: 'Ja — Genauigkeit exzellent', correct: false, xp: 0 }, { text: 'Ja, nur wöchentlich monitoren', correct: false, xp: 0 }, { text: 'Nein — Recall/Precision auf Betrugsklasse prüfen', correct: true, xp: 15 }, { text: 'Nein — unter 99 % nie ausreichend', correct: false, xp: 0 }], explanation: 'Immer-negativ-Baseline kann ~98 % erreichen; seltene Klasse entscheidet.' },

    { level: 'level2', topicIndex: 0, title: 'RGB + Infrarot-Backbone', description: 'Checkpoint soll laden; Eingaben haben 4 Kanäle (RGB+IR).', choices: [{ text: 'IR verwerfen, 3-Kanal-Gewichte', correct: false, xp: 0 }, { text: 'Erste Faltung auf 4 Kanäle anpassen, fine-tunen', correct: true, xp: 15 }, { text: 'Gesamtes Netz von vorn trainieren', correct: false, xp: 0 }, { text: 'In zwei 2-Kanal-Eingaben splitten', correct: false, xp: 0 }], explanation: 'Nur der Stem hängt von der Eingabetiefe ab.' },
    { level: 'level2', topicIndex: 1, title: '500 Röntgen-Thorax', description: 'Pneumonie; ImageNet-Backbone verfügbar. Stärkster Weg?', choices: [{ text: 'Von Grund auf trainieren', correct: false, xp: 0 }, { text: 'ImageNet, Backbone einfrieren, nur Kopf', correct: false, xp: 0 }, { text: 'ImageNet, alles mit kleiner LR freigeben', correct: false, xp: 0 }, { text: 'Medizinisches Pre-Training + differentielles Fine-Tuning wenn möglich', correct: true, xp: 15 }], explanation: 'Domänennahes Pre-Training schlägt Kleinst-Daten-Scratch.' },
    { level: 'level2', topicIndex: 2, title: 'Server + Mobile Klassifikatoren', description: 'Beste Server-Genauigkeit und leichte Mobile-Variante. Effizientester Gesamtweg?', choices: [{ text: 'Zwei Modelle komplett separat scratch', correct: false, xp: 0 }, { text: 'Großes Modell trainieren, mit Soft Targets destillieren', correct: true, xp: 15 }, { text: 'Nur kleines Modell auf allen Daten', correct: false, xp: 0 }, { text: 'Nur Pruning am großen Modell', correct: false, xp: 0 }], explanation: 'Destillation überträgt dunkles Wissen.' },
    { level: 'level2', topicIndex: 3, title: 'Dichtes Fischzählen', description: 'Fische in dichtem Unterwasservideo in Echtzeit (30 fps).', choices: [{ text: 'Zwei-Stufen-Detektor für max. Genauigkeit', correct: false, xp: 0 }, { text: 'Ein-Stufen anchor-free + Soft-NMS für Mengen', correct: true, xp: 15 }, { text: 'Klassifikator auf Ausschnitten', correct: false, xp: 0 }, { text: 'Nur semantische Segmentierung', correct: false, xp: 0 }], explanation: 'Geschwindigkeit + anchor-free + weichere NMS für Dichte.' },
    { level: 'level2', topicIndex: 4, title: 'Autobahn-Schilder', description: 'Ein-Skalen-Detektor verpasst kleine Schilder in 1280×720.', choices: [{ text: 'Eingabe immer verdoppeln', correct: false, xp: 0 }, { text: 'FPN für Mehrskalen-Features', correct: true, xp: 15 }, { text: 'Nur auf anchor-free wechseln', correct: false, xp: 0 }, { text: 'Flacheres Backbone', correct: false, xp: 0 }], explanation: 'FPN liefert hochauflösende Stufen für kleine Objekte.' },
    { level: 'level2', topicIndex: 5, title: 'Gedrehter Dokumenttext', description: 'Text 30°–45°; achsparallele Boxen verschwenden Hintergrund.', choices: [{ text: 'Standard-YOLO + aggressives NMS', correct: false, xp: 0 }, { text: 'DETR mit Standard-Queries', correct: false, xp: 0 }, { text: 'Rotierte Boxen (x, y, w, h, θ)', correct: true, xp: 15 }, { text: 'Semantik + achsparallele Box-Fit', correct: false, xp: 0 }], explanation: 'Orientierte Boxen straffen OCR-Crops.' },
    { level: 'level2', topicIndex: 6, title: 'Echtzeit-Spur', description: 'DeepLabv3+ groß: 12 fps; Ziel 30 fps auf Jetson.', choices: [{ text: 'Zu Instanzsegmentierung wechseln', correct: false, xp: 0 }, { text: 'Leichterer Encoder + einfacherer Decoder', correct: true, xp: 15 }, { text: 'Eingabe auf 32×32', correct: false, xp: 0 }, { text: 'Alle Skip-Verbindungen entfernen', correct: false, xp: 0 }], explanation: 'Leichte Encoder sind Standard für Echtzeit-Spuren.' },
    { level: 'level2', topicIndex: 7, title: 'Greifen am Band', description: 'Exakte Pixelgrenzen pro Objekt für Grasp, nicht nur Boxen.', choices: [{ text: 'Semantik + Heuristik', correct: false, xp: 0 }, { text: 'Nur Detection-Boxen', correct: false, xp: 0 }, { text: 'Instanzsegmentierungsmasken', correct: true, xp: 15 }, { text: 'Nur monokulare Tiefe', correct: false, xp: 0 }], explanation: 'Masken trennen berührende Objekte für Kontaktplanung.' },
    { level: 'level2', topicIndex: 8, title: 'Befahrbar plus Instanzen', description: 'Straße/Gehweg als „Stuff“, Fußgänger/Fahrzeuge als „Things“.', choices: [{ text: 'Nur semantisch', correct: false, xp: 0 }, { text: 'Nur Detection', correct: false, xp: 0 }, { text: 'Nur Instanz', correct: false, xp: 0 }, { text: 'Panoptische Segmentierung', correct: true, xp: 15 }], explanation: 'Panoptik vereint Regionen und zählbare Objekte.' },

    { level: 'level3', topicIndex: 0, title: 'Dichte Vorhersage bei 500k Bildern', description: 'CNN 78 % mIoU; ViT-B auf denselben Daten 75 %.', choices: [{ text: 'Blind auf ViT-H skalieren', correct: false, xp: 0 }, { text: 'Swin — hierarchisch, dateneffizienter für dichte Aufgaben', correct: true, xp: 15 }, { text: 'CNN gewinnt immer; aufhören', correct: false, xp: 0 }, { text: 'ViT-B von Grund auf auf 500k', correct: false, xp: 0 }], explanation: 'Swin liefert Pyramiden-Features für Segmentierung.' },
    { level: 'level3', topicIndex: 1, title: '2M ungelabelte Produkte', description: '5k Labels, feinkörnige Produkt-ID.', choices: [{ text: 'Nur überwachtes CNN auf 5k', correct: false, xp: 0 }, { text: 'MAE auf 2M, dann Fine-Tuning', correct: true, xp: 15 }, { text: 'Klassische Deskriptoren', correct: false, xp: 0 }, { text: 'k-Means-Cluster als Pseudo-Labels', correct: false, xp: 0 }], explanation: 'Self-Supervised nutzt unlabeled Skalierung.' },
    { level: 'level3', topicIndex: 2, title: 'Bewegung ohne vollen RAFT', description: 'Aktionsmodell braucht Bewegung; voller RAFT zu schwer bei 30 fps.', choices: [{ text: 'Rohe Pixeldifferenzen', correct: false, xp: 0 }, { text: 'Leichter Fluss oder seltener Fluss + Interpolation', correct: true, xp: 15 }, { text: 'Bewegung weglassen', correct: false, xp: 0 }, { text: 'RAFT nur jedes 10. Frame ohne Interpolation', correct: false, xp: 0 }], explanation: 'Günstiger Fluss oder Unterabtastung spart Rechenzeit.' },
    { level: 'level3', topicIndex: 3, title: 'Schnitt in langem OP-Video', description: '3 Stunden Video; spezifischer Schnitt; Genauigkeit wichtig, nicht Echtzeit.', choices: [{ text: 'Nur jedes 30. Frame klassifizieren', correct: false, xp: 0 }, { text: 'Grobe Szenenerkennung + zeitliche Lokalisierung mit starkem Video-Modell', correct: true, xp: 15 }, { text: 'Nur Fluss ohne Erscheinung', correct: false, xp: 0 }, { text: 'Nur Audio', correct: false, xp: 0 }], explanation: 'Zuerst eingrenzen, dann präzise zeitlich modellieren.' },
    { level: 'level3', topicIndex: 4, title: 'Tiefe für Lagerroboter', description: 'Ein Sensor; metrische Tiefe für Navigation.', choices: [{ text: 'Nur monokulares Self-Supervised', correct: false, xp: 0 }, { text: 'Stereo-RGB + gelerntes Matching', correct: true, xp: 15 }, { text: 'Nur 2D-LiDAR', correct: false, xp: 0 }, { text: 'Fisheye ohne Tiefe', correct: false, xp: 0 }], explanation: 'Stereo liefert metrische Tiefe kostengünstig.' },
    { level: 'level3', topicIndex: 5, title: 'Synthese seltener Defekte', description: '200 echte Defektfotos; mehr synthetische Vielfalt.', choices: [{ text: 'DDPM scratch mit 200', correct: false, xp: 0 }, { text: 'Latentes Diffusionsmodell fine-tunen (DreamBooth/LoRA)', correct: true, xp: 15 }, { text: 'Nur VAE-Interpolation', correct: false, xp: 0 }, { text: 'Nur nächster Nachbar-Augmentation', correct: false, xp: 0 }], explanation: 'Starke vortrainierte Generatoren anpassen.' },
    { level: 'level3', topicIndex: 6, title: 'VFX mit wenigen Ansichten', description: 'Fotoreal neue Ansichten; offline OK; Qualität oberste Priorität.', choices: [{ text: 'Klassische Mesh-Photogrammetrie nur', correct: false, xp: 0 }, { text: 'Moderne NeRF-Familie (z. B. Instant-NGP / Zip-NeRF)', correct: true, xp: 15 }, { text: 'Nur 3DGS, nie NeRF', correct: false, xp: 0 }, { text: 'Ein-Bild-Tiefe + Warping', correct: false, xp: 0 }], explanation: 'Implizite Felder für komplexe Appearance mit kalibrierten Views.' },
    { level: 'level3', topicIndex: 7, title: 'MCU-Klassifikation (512 KB Flash)', description: 'Kein FPU; Klassifikation auf Mikrocontroller.', choices: [{ text: 'ResNet-50 FP32', correct: false, xp: 0 }, { text: 'Tiefen-separables CNN + INT8-PTQ', correct: true, xp: 15 }, { text: 'Unstrukturiertes Pruning von ResNet-50', correct: false, xp: 0 }, { text: '8-Kopf-ViT FP32', correct: false, xp: 0 }], explanation: 'Kleine INT-taugliche Architekturen passen zu MCUs.' },

    { level: 'level4', topicIndex: 0, title: 'Defekt-Q&A Freitext', description: 'Nutzer laden Fotos hoch und fragen offen „Warum sieht die Oberfläche so aus?“', choices: [{ text: 'CLIP Zero-Shot mit festen Labels', correct: false, xp: 0 }, { text: 'Instruktions-feinjustiertes LVLM auf Domänenbildern', correct: true, xp: 15 }, { text: 'Klassisches VQA nur auf allgemeinen Benchmarks', correct: false, xp: 0 }, { text: 'Detektor + statische Tabelle', correct: false, xp: 0 }], explanation: 'Offene Erklärungen brauchen generative Multimodal-Modelle.' },
    { level: 'level4', topicIndex: 1, title: 'Sofa in neuen Szenen', description: '50 Sofa-Fotos; Nutzer: „Sofa im modernen Wohnzimmer.“', choices: [{ text: 'GAN scratch mit 50 Bildern', correct: false, xp: 0 }, { text: 'Gefrorene Diffusion + IP-Adapter + Textszene', correct: true, xp: 15 }, { text: 'Klassisches Compositing', correct: false, xp: 0 }, { text: 'Gesamte Diffusion auf 50 Bildern standardmäßig fine-tunen', correct: false, xp: 0 }], explanation: 'Erscheinungskonditionierung ohne ganzes UNet-Retraining.' },
    { level: 'level4', topicIndex: 2, title: 'Gesicht: Genauigkeit vs. Gruppe', description: '99,2 % Benchmark; 3× mehr False Accepts bei dunklerer Haut. Shippen?', choices: [{ text: 'Sofort; nur Gesamtgenauigkeit zählt', correct: false, xp: 0 }, { text: 'Verzögern; ausgewogene Daten, stratifizierte Ziele, Model Card', correct: true, xp: 15 }, { text: 'Nur Schwellen pro Gruppe', correct: false, xp: 0 }, { text: 'Demografische Merkmale aus Training löschen', correct: false, xp: 0 }], explanation: 'Disparate Fehler erfordern Mitigation und Dokumentation.' },
    { level: 'level4', topicIndex: 3, title: 'Plötzlich mehr False Negatives', description: 'Defektmodell wird schlechter; Monate kein Code-Change.', choices: [{ text: 'Stille Gewichtskorruption', correct: false, xp: 0 }, { text: 'Eingabe-Verteilungsdrift (Kamera/Licht) — Eingabe-Drift prüfen', correct: true, xp: 15 }, { text: 'GPU-Hardwarefehler', correct: false, xp: 0 }, { text: 'Trainingslabels in Produktion korrupt', correct: false, xp: 0 }], explanation: 'Sensor-/Umgebungswechsel sind typisch bei industrieller CV.' },
    { level: 'level4', topicIndex: 4, title: 'Recycling-Capstone', description: '2 Objekte/s, 24/7, eine Edge-GPU, >97 % je Klasse inkl. seltener Schmutz.', choices: [{ text: 'Nur CLIP Zero-Shot', correct: false, xp: 0 }, { text: 'ResNet-50 nur synthetisch, ohne Monitoring', correct: false, xp: 0 }, { text: 'Echte Banddaten, effizientes Backbone, Drift-Monitoring, Hard-Negative-Loop', correct: true, xp: 15 }, { text: 'Panoptik zum Sortieren', correct: false, xp: 0 }], explanation: 'Produktion braucht Domänendaten, Effizienz und kontinuierliche Verbesserung.' }
]);
